name: Test

on: pull_request

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install Dependecies
        run: npm install
      - name: Run Unit Tests
        run: ng test --no-watch --no-progress --browsers=ChromeHeadless
